import React, { useRef, useState } from 'react';
import { ValidationReport } from '../types';
import { Card } from '../components/Card';
import { ScoreGauge } from '../components/ScoreGauge';
import { Button } from '../components/Button';
import { 
  CheckCircle2, 
  AlertTriangle, 
  Share2, 
  RefreshCcw, 
  Download,
  Loader2,
  MessageSquare
} from 'lucide-react';
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import ReactMarkdown from 'react-markdown';

interface ReportViewProps {
  report: ValidationReport;
  onReset: () => void;
  onUpgrade: () => void;
  onChat: () => void;
}

export const ReportView: React.FC<ReportViewProps> = ({ report, onReset, onUpgrade, onChat }) => {
  const [isDownloading, setIsDownloading] = useState(false);
  const [isShared, setIsShared] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  const getVerdictColor = (verdict: string) => {
    switch (verdict) {
      case 'Promising': return 'bg-emerald-100 text-emerald-800 border-emerald-200';
      case 'Risky': return 'bg-rose-100 text-rose-800 border-rose-200';
      default: return 'bg-amber-100 text-amber-800 border-amber-200';
    }
  };

  const handleShare = async () => {
    const shareText = `🚀 ZauriScore Report\n\nVerdict: ${report.summaryVerdict.toUpperCase()}\nScore: ${report.viabilityScore}/100\n\n"${report.oneLineTakeaway}"\n\nMarket Reality: ${report.marketReality}\n\nGenerated by ZauriScore.`;

    // Try Native Share
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Startup Validation Report',
          text: shareText,
        });
        return;
      } catch (err) {
        // If user cancels or it fails, fall back to clipboard
        if ((err as Error).name === 'AbortError') return;
      }
    }

    // Fallback: Copy to Clipboard
    try {
      await navigator.clipboard.writeText(shareText);
      setIsShared(true);
      setTimeout(() => setIsShared(false), 2000);
    } catch (err) {
      alert("Failed to copy to clipboard.");
    }
  };

  const handleDownloadPDF = async () => {
    if (!reportRef.current) return;
    setIsDownloading(true);

    try {
        // Capture the DOM element
        const canvas = await html2canvas(reportRef.current, {
            scale: 2, // Improve resolution
            useCORS: true, // Handle external images if any
            logging: false,
            backgroundColor: '#f8fafc', // Match the app background
            windowWidth: 1200 // Force desktop width for consistent layout
        });

        const imgData = canvas.toDataURL('image/png');
        
        // A4 Dimensions (mm)
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();
        
        // Calculate image height based on A4 width
        const imgHeight = (canvas.height * pdfWidth) / canvas.width;
        
        let heightLeft = imgHeight;
        let position = 0;

        // First page
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, imgHeight);
        heightLeft -= pdfHeight;

        // Additional pages if content overflows
        while (heightLeft > 0) {
            position -= pdfHeight;
            pdf.addPage();
            pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, imgHeight);
            heightLeft -= pdfHeight;
        }

        pdf.save(`validation-report-${report.id.slice(0, 8)}.pdf`);
    } catch (error) {
        console.error("PDF generation failed", error);
        alert("Failed to generate PDF. Please try again.");
    } finally {
        setIsDownloading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto pb-20 px-4">
      
      {/* Header Actions */}
      <div className="flex flex-col sm:flex-row justify-between items-center py-6 mb-4 gap-4">
        <div className="flex gap-2 w-full sm:w-auto">
          <Button variant="outline" size="sm" onClick={onReset} className="gap-2 flex-1 sm:flex-none justify-center">
            <RefreshCcw size={16} /> New Idea
          </Button>
          <Button onClick={onChat} className="gap-2 flex-1 sm:flex-none justify-center bg-slate-900 text-white shadow-lg shadow-slate-900/20 hover:shadow-xl hover:shadow-slate-900/30 transition-all">
             <MessageSquare size={16} /> Deep Dive Chat
          </Button>
        </div>
        
        <div className="flex gap-2 w-full sm:w-auto">
            <Button 
                variant="outline" 
                size="sm" 
                className="gap-2 flex-1 sm:flex-none justify-center" 
                onClick={handleDownloadPDF}
                disabled={isDownloading}
            >
                {isDownloading ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />} 
                {isDownloading ? "Generating..." : "PDF"}
            </Button>
            <Button 
                variant="outline" 
                size="sm" 
                className={`gap-2 transition-all flex-1 sm:flex-none justify-center ${isShared ? 'bg-emerald-50 text-emerald-600 border-emerald-200' : ''}`} 
                onClick={handleShare}
            >
                {isShared ? <CheckCircle2 size={16} /> : <Share2 size={16} />} 
                {isShared ? "Copied!" : "Share"}
            </Button>
        </div>
      </div>

      {/* Content to Print */}
      <div ref={reportRef} id="report-content" className="space-y-8">
        {/* Main Verdict Card */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-8">
            <div className="flex flex-col md:flex-row gap-8 items-center">
            <div className="flex-1">
                <div className={`inline-flex px-3 py-1 rounded-full text-sm font-semibold border mb-4 ${getVerdictColor(report.summaryVerdict)}`}>
                {report.summaryVerdict.toUpperCase()}
                </div>
                <h1 className="text-3xl font-bold text-slate-900 mb-4">Idea Validation Report</h1>
                <p className="text-xl text-slate-600 leading-relaxed font-medium">
                "{report.oneLineTakeaway}"
                </p>
            </div>
            <div className="shrink-0">
                <ScoreGauge score={report.viabilityScore} />
            </div>
            </div>
        </div>

        {/* Grid Layout */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* Market Reality */}
            <Card title="Market Reality" className="md:col-span-2">
              <div className="prose prose-slate max-w-none text-slate-700 leading-relaxed text-sm">
                <ReactMarkdown>{report.marketReality}</ReactMarkdown>
              </div>
            </Card>

            {/* Pros */}
            <Card title="Strengths">
            <ul className="space-y-4">
                {report.pros.map((pro, i) => (
                <li key={i} className="flex gap-3 items-start">
                    <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" />
                    <span className="text-slate-700 text-sm">
                      <ReactMarkdown components={{ p: ({children}) => <span>{children}</span> }}>
                        {pro}
                      </ReactMarkdown>
                    </span>
                </li>
                ))}
            </ul>
            </Card>

            {/* Cons */}
            <Card title="Risks">
            <ul className="space-y-4">
                {report.cons.map((con, i) => (
                <li key={i} className="flex gap-3 items-start">
                    <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
                    <span className="text-slate-700 text-sm">
                       <ReactMarkdown components={{ p: ({children}) => <span>{children}</span> }}>
                        {con}
                      </ReactMarkdown>
                    </span>
                </li>
                ))}
            </ul>
            </Card>

            {/* Competitors */}
            <Card title="Who's already doing this">
            <div className="space-y-4">
                {report.competitors.map((comp, i) => (
                <div key={i} className="p-3 bg-slate-50 rounded-lg border border-slate-100">
                    <div className="font-semibold text-slate-900 text-sm">{comp.name}</div>
                    <div className="text-slate-500 text-xs mt-1">{comp.differentiation}</div>
                </div>
                ))}
            </div>
            </Card>

            {/* Monetization */}
            <Card title="How to make money">
            <div className="mb-4">
                <div className="flex flex-wrap gap-2 mb-4">
                {report.monetizationStrategies.map((strat, i) => (
                    <span key={i} className="px-3 py-1 bg-blue-50 text-blue-700 text-xs font-medium rounded-full border border-blue-100">
                    {strat}
                    </span>
                ))}
                </div>
            </div>
            <div className="pt-4 border-t border-slate-100">
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wide mb-2">Why users pay</h4>
                <p className="text-sm text-slate-700 italic">"{report.whyPeoplePay}"</p>
            </div>
            </Card>

            {/* Next Steps */}
            <Card title="Action Plan" className="md:col-span-2 bg-slate-900 border-slate-900">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {report.nextSteps.map((step, i) => (
                <div key={i} className="flex gap-3 p-4 bg-slate-800 rounded-lg border border-slate-700">
                    <div className="w-6 h-6 rounded-full bg-slate-700 flex items-center justify-center shrink-0 text-slate-300 font-bold text-xs">
                    {i + 1}
                    </div>
                    <span className="text-slate-200 text-sm font-medium">
                      <ReactMarkdown components={{ p: ({children}) => <span>{children}</span> }}>
                        {step}
                      </ReactMarkdown>
                    </span>
                </div>
                ))}
            </div>
            </Card>

        </div>
        
        {/* Upsell / Footer included in PDF */}
        <div className="text-center py-12 border-t border-slate-200 bg-slate-50 rounded-xl">
            <h3 className="text-lg font-semibold text-slate-900 mb-2">Build confident. Validate often.</h3>
            <p className="text-slate-500 mb-6">Generated by ZauriScore.</p>
        </div>
      </div>
    </div>
  );
};